name: release-github

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ["ubuntu-latest"]
    container: "westonrobot/ubuntu:jammy-ci-latest"
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: westonrobot-dev/release-action@v1.13.0
        with:
          generateReleaseNotes: true